name: Github Action Examples of spring project

on:
  push:
    branch:
      - spring-actions

jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: install mvn 
        run: mvn clean install         
      - name: login to github container registry
        uses: docker/login-action@v1
        with:
           registry: ghcr.io
           username: bharti2022
           password: ${{secrets.REPO_TOKEN}}
      - name: docker build
        run: docker build . -t ghcr.io/bharti2022/sample-spring-app:latest
      - name: docker push  
        run: docker push ghcr.io/bharti2022/sample-spring-app:latest
